### ISSUE TITLE
Make `healthz` / `readyz` of `KubeAPIServer` not require authentication

### ISSUE THREAD

**Issue by adracus** [onmetal/matryoshka#38]
# Summary

When creating the [health probes](https://github.com/onmetal/matryoshka/blob/3583afc69010c83840d2ef1d8592bacc680c7663/controllers/matryoshka/internal/kubeapiserver/kubeapiserver.go#L349), we use some unreliable means of inferring credentials. We should come up with a more reliable means that also don't leak confidential information as part of health probe headers.

The task is deliberately designed to be open: The developer assigned should come up with an own solution and take investigations in the Kubernetes ecosystem to find a maintainable and secure solution.

Some ideas (please don't limit yourself to them) for potential solutions are:
* Health check sidecar that uses secrets / shared volumes with API server
* Always allow `/healthz` / `/readyz` calls and document accordingly

# Definition of Done

* The health checks don't expose authorization headers anymore
* The health checks are more reliable (don't just randomly choose some auth header)
* Code is tested and documented

**Comment by GrigoriyMikhalkin** [comment]
Here i will describe my progress so far. Yesterday i thought i was really close -- i tried to use Secret provided by user and use token in exec command. I was very much wrong about this ;( -- turns out kubeapiserver image is based on `scratch` or some other bare naked image and doesn't contain any shell. So I'm not able to use environment variable defined from a Secret's key.
